name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [  main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Clean cache
      run: npm cache clean --force 

    - name: Install dependencies
      run: npm install

    - run: CI=false npm run build

    - name: Install react-scripts
      run: npm install react-scripts

    - name: Build
      run: npm run build